#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

BIN_PATH="/tmp/cloudflared"
DL_URL="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64"
CONFIG_PATH="/root/.cloudflared/config.yml"

start_service() {

    if [ ! -x "$BIN_PATH" ]; then
        logger -t cloudflared "Downloading binary to RAM..."


        wget -q -O "$BIN_PATH" "$DL_URL"


        if [ $? -ne 0 ]; then
            logger -t cloudflared "Error: Download failed. Will retry via procd."

            rm -f "$BIN_PATH"

            return 1
        fi


        chmod +x "$BIN_PATH"
        logger -t cloudflared "Download successful."
    fi


    procd_open_instance

    procd_set_param command "$BIN_PATH" tunnel --no-autoupdate --config "$CONFIG_PATH" run

    procd_set_param respawn 3600 5 5

    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_close_instance
}

stop_service() {
    logger -t cloudflared "Stopping tunnel..."
}
