theme: jekyll-theme-slate
url: "https://zakerru.site"
baseurl: ""

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
title: My roadmap projects
description: Reports on roadmap.sh projects
include:
  - folder_cleaner
  - statistics-script
  - static-site-server
  - ssh_remote_setup
  - Nginx_analiser
  - pages-deployment
  - workflow-miniprojects
  - simple-monitoring
  - Systemd-Service
  - DNS-Setup
  - Docker
