server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    index index1.html;

    access_log /var/log/nginx/nginx-access.log;

    location / {
        try_files $uri $uri/ =404;
    }

    location /stub_status {
        stub_status;
        allow all;
    }
}
