global:
  dockerUsername: "zakerru78@gmail.com"

parser:
  imageName: "parser"
  enabled: true
  imageTag: "a1b2c3d"

sites:
  site1:
    enabled: true
    replicas: 2
    imageTag: "a1b2c3d"

  site2:
    enabled: true
    replicas: 1
    imageTag: "a1b2c3d"

  site3:
    enabled: false
    replicas: 0
    imageTag: "a1b2c3d"

  site4:
    enabled: true
    replicas: 1
    imageTag: "a1b2c3d"
