global:
  dockerUsername: "zakerru"
parser:
  imageName: "parser"
  enabled: true
  imageTag: "132a9a2"
sites:
  site1:
    enabled: true
    replicas: 2
    imageTag: "50f4af9"
  site2:
    enabled: true
    replicas: 1
    imageTag: "50f4af9"
  site3:
    enabled: false
    replicas: 0
    imageTag: "50f4af9"
  site4:
    enabled: true
    replicas: 1
    imageTag: "50f4af9"
