#Directory from which the files will be moved for archiving
out_dir=""
#Directory where the files will be moved and archived
in_dir=""
#How old should be files
file_age=""
#How old should be archives
arch_age=""

