name: autostats

on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: running
      run: |
        chmod +x statistics-script/server-stats.sh
        ./statistics-script/server-stats.sh >> workflow-miniprojects/stats.log 2>&1
        git config user.name "GitHub Actions Bot"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add workflow-miniprojects/stats.log
        git diff-index --quiet HEAD || (git commit -m "Auto-update system report" && git push origin main)
