services:
  nginx:
    build: ./pod1/site1doc
    container_name: my-running-site1
    ports:
      - "8081:80"
    volumes:
      - nginx_logs:/mylogs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  netdata:
    image: netdata/netdata
    container_name: netdata
    ports:
      - "19999:19999"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./netdatadoc/nginx.conf:/etc/netdata/go.d/nginx.conf
      - ./netdatadoc/netdata.conf:/etc/netdata/netdata.conf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    depends_on:
      - nginx



volumes:
  nginx_logs:
